### ISSUE TITLE
Following the build instructions doesn't yield valid results

### ISSUE THREAD

**Issue by tym2k1** [3mdeb/RteCtrl#19]
As the title says

```sh
$ mkdir -p ~/go/src/3mdeb && cd ~/go/src/3mdeb
~/go/src/3mdeb$ git clone git@github.com:3mdeb/RteCtrl.git
~/go/src/3mdeb$ cd RteCtrl
~/go/src/3mdeb/RteCtrl$ make
go get github.com/gorilla/mux
make: go: No such file or directory
make: *** [Makefile:25: deps] Error 127
```

No dependancies are specified for manual building. A solution for this could be providing a Container with correct dependancies like Go version. Such container could be utilized also for the CI/CD issue https://github.com/3mdeb/RteCtrl/issues/18.

**Comment by macpijan** [comment]
> make: go: No such file or directory

Well, it's hard to build golang app without Go compiler indeed.

Here's a container if you need it: https://hub.docker.com/_/golang

You can deduce version which used to work back then in Travis here if needed: https://github.com/3mdeb/RteCtrl/blob/master/.travis.yml#L4

**Comment by tym2k1** [comment]
:facepalm: :facepalm: :facepalm:

Yeah, my bad. I might've had a temporary stroke. It builds fine with the newest `v1.22.5`.

Closing the issue
