### ISSUE TITLE
RteCtrl works inappropriately

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [3mdeb/RteCtrl#6]
`RteCtrl` service, which is available on RTE meta-rte version 0.7.1 works inappropriately.

1. Command `RteCtrl -rel` allows only to turn on the relay, when it should allow to turn on and off it.
2. Command `RteCtrl -poff` allows to turn off the relay, when it should only change the state of the dedicated pin.
3. Command `RteCtrl -reset` allows to turn off the relay, when it should only change the state of the dedicated pin. 

In my opinion, RteCtrl should work as follows:
1. `RteCtrl -rel` should be dedicated to controlling the relay only, each time this command is called, the relay should change its state.
2. `RteCtrl -pon` should be dedicated only to turning on the connected platform. This might be done by changing the state of one of the pins for 1 second.
3. `RteCtrl -poff` should be dedicated only to turning off the connected platform. This might be done by changing the state of one of the pins for 5 seconds.
4. `RteCtrl -reset` should be dedicated only to resetting the connected platform. This might be done by changing the state of one of the pins (not the same as the pin in points 2 and 3) for 1 second.

**Comment by macpijan** [comment]
The assumptions were incorrect, not the execution.
It works as a server, it should be started once and then called via API.
